### ISSUE TITLE
Ctrl + Shift + K Следующая страница. 

### ISSUE THREAD

**Issue by ve1mi** [vandy/handy-search#1]
Notion Web Clipper имеет такую комбинацию клавиш, может назначите на другое? И почему вы не указали в описание, как управлять мышью, это так задумано: зажать лкм, чтобы получить список?

**Comment by vandy** [comment]
`Ctrl+Shift+K` - это желаемая комбинация клавиш для расширения. Вы можете настроить свою комбинацию в настройках расширений браузера:

- `Settings -> More Tools -> Extensions`, в верхней части будет кнопка-бутерброд, чтобы перейти на страницу `Keyboard shortcuts`, где можно установить такую комбинацию, которая будет работать у вас.

- Либо правой кнопкой на иконке расширения (рядом с адресной строкой), далее `Manage Extensions` (последний пункт контекстного меню) и та же кнопка-бутерброд, указанная в предыдущем пункте.

Вы правы, не совсем явный алгоритм с предлагаемыми страницами, укажу в описании. Все работает так, как вы описали: короткое нажатие лкм - переход на другую страницу, длинное нажатие лкм - появляется список всех предлагаемых страниц. (Аналогично можно использовать клавиатуру (Пробел) вместо лкм). Можно использовать среднюю кнопку мыши, чтобы открывать в новой вкладке.

Полагаю этот issue можно закрыть?
